scalar DateTime

type Tag {
  photoId: ID!
  userId: ID!
}

type Photo {
  id: ID!
  created: DateTime!
  category: PhotoCategory!
  url: String!
  name: String!
  description: String
  postedBy: User!
  githubUser: String!
  taggedUsers: [User!]!
}

enum PhotoCategory {
  SELFIE
  PORTRAIT
  ACTION
  LANDSCAPE
  GRAPHIC
}

type User {
  githubLogin: ID!
  name: String
  avatar: String
  postedPhotos: [Photo!]!
  inPhotos: [Photo!]!
}

type Query {
  totalPhotos: Int!
  allPhotos(after: DateTime): [Photo!]!
  totalUsers: Int!
  allUsers: [User!]!
  totalTags: Int!
  allTags: [Tag!]!
}

type Mutation {
  postPhoto(input: PostPhotoInput!): Photo!
}

input PostPhotoInput {
  name: String!
  category: PhotoCategory=PORTRAIT
  description: String
}
